### ISSUE TITLE
Embedded Tooltips - Damage values aren't accurate

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-react#190]
This will require a lot of work. Adding the issue here so it's logged.

![damage_one](https://cloud.githubusercontent.com/assets/6556434/23514117/ae98948c-ff3c-11e6-992c-313577202156.png)

**Comment by DxCx** [comment]
this is because the skill fact returns `hit_count: 1`
i think that for Damage we need to add some calculation formula.
i can do it dummy so it will show exactly as Gw2Wiki (1 hit count = 266 dmg)
so (266 * data.hit_count * data. dmg_multiplier) (in this case both are 1)
https://wiki.guildwars2.com/wiki/%22Feel_the_Burn!%22

please enlighten me if you have a better way of solving this..

**Comment by madou** [comment]
im happy using the 1 hit count = 266 damage, easiest and most straight forward. 

would be good to get proper calculations in the armory side of things when viewing someones character, but uh, maybe later..

**Comment by DxCx** [comment]
alright, thanks, done.
